services:
  mt5docker:
    build: .
    image: mt5docker:local
    container_name: mt5docker
    environment:
      - MT5_HOST=
      - VNC_PWD=QuickPass@1245
    ports:
      - 5901:5901
      - 6081:6081
      - 8001:8001
    restart: "no"
    stdin_open: true
    tty: true
